/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddAppInput
 */
export interface AddAppInput {
    /**
     * 名称
     * @type {string}
     * @memberof AddAppInput
     */
    name: any;
    /**
     * 编码
     * @type {string}
     * @memberof AddAppInput
     */
    code: any;
    /**
     * 是否默认激活（Y-是，N-否）,只能有一个系统默认激活  用户登录后默认展示此系统菜单
     * @type {string}
     * @memberof AddAppInput
     */
    active?: any | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof AddAppInput
     */
    status?: any;
    /**
     * 排序
     * @type {number}
     * @memberof AddAppInput
     */
    sort?: any;
}
