/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddNoticeInput
 */
export interface AddNoticeInput {
    /**
     * 标题
     * @type {string}
     * @memberof AddNoticeInput
     */
    title: any;
    /**
     * 内容
     * @type {string}
     * @memberof AddNoticeInput
     */
    content: any;
    /**
     * 类型（字典 1通知 2公告）
     * @type {number}
     * @memberof AddNoticeInput
     */
    type: any;
    /**
     * 
     * @type {NoticeStatus}
     * @memberof AddNoticeInput
     */
    status: any;
    /**
     * 通知到的人
     * @type {Array&lt;number&gt;}
     * @memberof AddNoticeInput
     */
    noticeUserIdList: any;
}
