/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddJobInput
 */
export interface AddJobInput {
    /**
     * 任务名称
     * @type {string}
     * @memberof AddJobInput
     */
    jobName?: any | null;
    /**
     * 只执行一次
     * @type {boolean}
     * @memberof AddJobInput
     */
    doOnce?: any;
    /**
     * 立即执行（默认等待启动）
     * @type {boolean}
     * @memberof AddJobInput
     */
    startNow?: any;
    /**
     * 
     * @type {SpareTimeExecuteTypes}
     * @memberof AddJobInput
     */
    executeType?: any;
    /**
     * 执行间隔时间（单位秒）
     * @type {number}
     * @memberof AddJobInput
     */
    interval?: any;
    /**
     * Cron表达式
     * @type {string}
     * @memberof AddJobInput
     */
    cron?: any | null;
    /**
     * 
     * @type {SpareTimeTypes}
     * @memberof AddJobInput
     */
    timerType?: any;
    /**
     * 请求url
     * @type {string}
     * @memberof AddJobInput
     */
    requestUrl?: any | null;
    /**
     * 请求参数（Post，Put请求用）
     * @type {string}
     * @memberof AddJobInput
     */
    requestParameters?: any | null;
    /**
     * Headers(可以包含如：Authorization授权认证)  格式：{\"Authorization\":\"userpassword..\"}
     * @type {string}
     * @memberof AddJobInput
     */
    headers?: any | null;
    /**
     * 
     * @type {RequestTypeEnum}
     * @memberof AddJobInput
     */
    requestType?: any;
    /**
     * 备注
     * @type {string}
     * @memberof AddJobInput
     */
    remark?: any | null;
}
