/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 代码生成详细配置参数
 * @export
 * @interface CodeGenConfig
 */
export interface CodeGenConfig {
    /**
     * 主键Id
     * @type {number}
     * @memberof CodeGenConfig
     */
    id?: any;
    /**
     * 代码生成主表ID
     * @type {number}
     * @memberof CodeGenConfig
     */
    codeGenId?: any;
    /**
     * 数据库字段名
     * @type {string}
     * @memberof CodeGenConfig
     */
    columnName?: any | null;
    /**
     * 数据库字段名(首字母小写)
     * @type {string}
     * @memberof CodeGenConfig
     */
    lowerColumnName?: any | null;
    /**
     * 字段描述
     * @type {string}
     * @memberof CodeGenConfig
     */
    columnComment?: any | null;
    /**
     * .NET类型
     * @type {string}
     * @memberof CodeGenConfig
     */
    netType?: any | null;
    /**
     * 作用类型（字典）
     * @type {string}
     * @memberof CodeGenConfig
     */
    effectType?: any | null;
    /**
     * 外键实体名称
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkEntityName?: any | null;
    /**
     * 外键实体名称(首字母小写)
     * @type {string}
     * @memberof CodeGenConfig
     */
    lowerFkEntityName?: any | null;
    /**
     * 外键显示字段
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkColumnName?: any | null;
    /**
     * 外键显示字段(首字母小写)
     * @type {string}
     * @memberof CodeGenConfig
     */
    lowerFkColumnName?: any | null;
    /**
     * 外键显示字段.NET类型
     * @type {string}
     * @memberof CodeGenConfig
     */
    fkColumnNetType?: any | null;
    /**
     * 字典code
     * @type {string}
     * @memberof CodeGenConfig
     */
    dictTypeCode?: any | null;
    /**
     * 列表是否缩进（字典）
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherRetract?: any | null;
    /**
     * 是否必填（字典）
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherRequired?: any | null;
    /**
     * 是否是查询条件
     * @type {string}
     * @memberof CodeGenConfig
     */
    queryWhether?: any | null;
    /**
     * 查询方式
     * @type {string}
     * @memberof CodeGenConfig
     */
    queryType?: any | null;
    /**
     * 列表显示
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherTable?: any | null;
    /**
     * 列表排序显示
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherOrderBy?: any | null;
    /**
     * 增改
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherAddUpdate?: any | null;
    /**
     * 主外键
     * @type {string}
     * @memberof CodeGenConfig
     */
    columnKey?: any | null;
    /**
     * 数据库中类型（物理类型）
     * @type {string}
     * @memberof CodeGenConfig
     */
    dataType?: any | null;
    /**
     * 是否是通用字段
     * @type {string}
     * @memberof CodeGenConfig
     */
    whetherCommon?: any | null;
}
