/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 字典类型与字典值构造的树
 * @export
 * @interface DictTreeOutput
 */
export interface DictTreeOutput {
    /**
     * Id
     * @type {number}
     * @memberof DictTreeOutput
     */
    id?: any;
    /**
     * 父Id
     * @type {number}
     * @memberof DictTreeOutput
     */
    pid?: any;
    /**
     * 编码-对应字典值的编码
     * @type {string}
     * @memberof DictTreeOutput
     */
    code?: any | null;
    /**
     * 名称-对应字典值的value
     * @type {string}
     * @memberof DictTreeOutput
     */
    name?: any | null;
    /**
     * 子节点集合
     * @type {Array&lt;DictTreeOutput&gt;}
     * @memberof DictTreeOutput
     */
    children?: any | null;
}
