/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 附属机构和职位参数
 * @export
 * @interface EmpExtOrgPosOutput
 */
export interface EmpExtOrgPosOutput {
    /**
     * 附属机构id
     * @type {number}
     * @memberof EmpExtOrgPosOutput
     */
    orgId?: any;
    /**
     * 附属机构编码
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    orgCode?: any | null;
    /**
     * 附属机构名称
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    orgName?: any | null;
    /**
     * 附属职位id
     * @type {number}
     * @memberof EmpExtOrgPosOutput
     */
    posId?: any;
    /**
     * 附属职位编码
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    posCode?: any | null;
    /**
     * 附属职位名称
     * @type {string}
     * @memberof EmpExtOrgPosOutput
     */
    posName?: any | null;
}
