/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 登陆类型<br />&nbsp;登陆 LOGIN = LOGIN<br />&nbsp;登出 LOGOUT = LOGOUT<br />&nbsp;注册 REGISTER = REGISTER<br />&nbsp;改密 CHANGEPASSWORD = CHANGEPASSWORD<br />&nbsp;授权登陆 AUTHORIZEDLOGIN = AUTHORIZEDLOGIN<br />
 * @export
 * @enum {string}
 */
export enum LoginType {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}

