/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 用户登录输出参数
 * @export
 * @interface LoginOutput
 */
export interface LoginOutput {
    /**
     * 主键
     * @type {number}
     * @memberof LoginOutput
     */
    id?: any;
    /**
     * 账号
     * @type {string}
     * @memberof LoginOutput
     */
    account?: any | null;
    /**
     * 昵称
     * @type {string}
     * @memberof LoginOutput
     */
    nickName?: any | null;
    /**
     * 姓名
     * @type {string}
     * @memberof LoginOutput
     */
    name?: any | null;
    /**
     * 头像
     * @type {string}
     * @memberof LoginOutput
     */
    avatar?: any | null;
    /**
     * 生日
     * @type {Date}
     * @memberof LoginOutput
     */
    birthday?: any;
    /**
     * 性别(字典 1男 2女)
     * @type {number}
     * @memberof LoginOutput
     */
    sex?: any;
    /**
     * 邮箱
     * @type {string}
     * @memberof LoginOutput
     */
    email?: any | null;
    /**
     * 手机
     * @type {string}
     * @memberof LoginOutput
     */
    phone?: any | null;
    /**
     * 电话
     * @type {string}
     * @memberof LoginOutput
     */
    tel?: any | null;
    /**
     * 管理员类型（0超级管理员 1非管理员）
     * @type {number}
     * @memberof LoginOutput
     */
    adminType?: any;
    /**
     * 最后登陆IP
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginIp?: any | null;
    /**
     * 最后登陆时间
     * @type {Date}
     * @memberof LoginOutput
     */
    lastLoginTime?: any;
    /**
     * 最后登陆地址
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginAddress?: any | null;
    /**
     * 最后登陆所用浏览器
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginBrowser?: any | null;
    /**
     * 最后登陆所用系统
     * @type {string}
     * @memberof LoginOutput
     */
    lastLoginOs?: any | null;
    /**
     * 
     * @type {EmpOutput}
     * @memberof LoginOutput
     */
    loginEmpInfo?: any;
    /**
     * 具备应用信息
     * @type {Array&lt;AppOutput&gt;}
     * @memberof LoginOutput
     */
    apps?: any | null;
    /**
     * 角色信息
     * @type {Array&lt;RoleOutput&gt;}
     * @memberof LoginOutput
     */
    roles?: any | null;
    /**
     * 权限信息
     * @type {Array&lt;string&gt;}
     * @memberof LoginOutput
     */
    permissions?: any | null;
    /**
     * 登录菜单信息---AntDesign版本菜单
     * @type {Array&lt;AntDesignTreeNode&gt;}
     * @memberof LoginOutput
     */
    menus?: any | null;
    /**
     * 数据范围（机构）信息
     * @type {Array&lt;number&gt;}
     * @memberof LoginOutput
     */
    dataScopes?: any | null;
}
