/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 系统通知公告详情参数
 * @export
 * @interface NoticeDetailOutput
 */
export interface NoticeDetailOutput {
    /**
     * 标题
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    title?: any | null;
    /**
     * 内容
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    content?: any | null;
    /**
     * 类型（字典 1通知 2公告）
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    type?: any;
    /**
     * 发布人Id
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    publicUserId?: any;
    /**
     * 发布人姓名
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    publicUserName?: any | null;
    /**
     * 发布机构Id
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    publicOrgId?: any;
    /**
     * 发布机构名称
     * @type {string}
     * @memberof NoticeDetailOutput
     */
    publicOrgName?: any | null;
    /**
     * 发布时间
     * @type {Date}
     * @memberof NoticeDetailOutput
     */
    publicTime?: any;
    /**
     * 撤回时间
     * @type {Date}
     * @memberof NoticeDetailOutput
     */
    cancelTime?: any;
    /**
     * 状态（字典 0草稿 1发布 2撤回 3删除）
     * @type {number}
     * @memberof NoticeDetailOutput
     */
    status?: any;
    /**
     * 通知到的用户Id集合
     * @type {Array&lt;string&gt;}
     * @memberof NoticeDetailOutput
     */
    noticeUserIdList?: any | null;
    /**
     * 通知到的用户阅读信息集合
     * @type {Array&lt;NoticeUserRead&gt;}
     * @memberof NoticeDetailOutput
     */
    noticeUserReadInfoList?: any | null;
}
