/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * <br />&nbsp;并行执行 Parallel = Parallel<br />&nbsp;串行执行 Serial = Serial<br />
 * @export
 * @enum {string}
 */
export enum SpareTimeExecuteTypes {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

