/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 代码生成字段配置表
 * @export
 * @interface SysCodeGenConfig
 */
export interface SysCodeGenConfig {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    id?: any;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysCodeGenConfig
     */
    createdTime?: any | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof SysCodeGenConfig
     */
    updatedTime?: any | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    createdUserId?: any | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    createdUserName?: any | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    updatedUserId?: any | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    updatedUserName?: any | null;
    /**
     * 代码生成主表ID
     * @type {number}
     * @memberof SysCodeGenConfig
     */
    codeGenId?: any;
    /**
     * 数据库字段名
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnName: any;
    /**
     * 字段描述
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnComment?: any | null;
    /**
     * .NET数据类型
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    netType?: any | null;
    /**
     * 作用类型（字典）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    effectType?: any | null;
    /**
     * 外键实体名称
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkEntityName?: any | null;
    /**
     * 外键显示字段
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkColumnName?: any | null;
    /**
     * 外键显示字段.NET类型
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    fkColumnNetType?: any | null;
    /**
     * 字典code
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    dictTypeCode?: any | null;
    /**
     * 列表是否缩进（字典）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherRetract?: any | null;
    /**
     * 是否必填（字典）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherRequired?: any | null;
    /**
     * 是否是查询条件
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    queryWhether?: any | null;
    /**
     * 查询方式
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    queryType?: any | null;
    /**
     * 列表显示
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherTable?: any | null;
    /**
     * 列表是否排序
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherOrderBy?: any | null;
    /**
     * 增改
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherAddUpdate?: any | null;
    /**
     * 主键
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    columnKey?: any | null;
    /**
     * 数据库中类型（物理类型）
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    dataType?: any | null;
    /**
     * 是否通用字段
     * @type {string}
     * @memberof SysCodeGenConfig
     */
    whetherCommon?: any | null;
}
