/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 角色数据范围表
 * @export
 * @interface SysRoleDataScope
 */
export interface SysRoleDataScope {
    /**
     * 角色Id
     * @type {number}
     * @memberof SysRoleDataScope
     */
    sysRoleId?: any;
    /**
     * 
     * @type {SysRole}
     * @memberof SysRoleDataScope
     */
    sysRole?: any;
    /**
     * 机构Id
     * @type {number}
     * @memberof SysRoleDataScope
     */
    sysOrgId?: any;
    /**
     * 
     * @type {SysOrg}
     * @memberof SysRoleDataScope
     */
    sysOrg?: any;
}
