/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 角色菜单表
 * @export
 * @interface SysRoleMenu
 */
export interface SysRoleMenu {
    /**
     * 角色Id
     * @type {number}
     * @memberof SysRoleMenu
     */
    sysRoleId?: any;
    /**
     * 
     * @type {SysRole}
     * @memberof SysRoleMenu
     */
    sysRole?: any;
    /**
     * 菜单Id
     * @type {number}
     * @memberof SysRoleMenu
     */
    sysMenuId?: any;
    /**
     * 
     * @type {SysMenu}
     * @memberof SysRoleMenu
     */
    sysMenu?: any;
}
