/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 用户表
 * @export
 * @interface SysUser
 */
export interface SysUser {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysUser
     */
    id?: any;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysUser
     */
    createdTime?: any | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof SysUser
     */
    updatedTime?: any | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysUser
     */
    createdUserId?: any | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysUser
     */
    createdUserName?: any | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysUser
     */
    updatedUserId?: any | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysUser
     */
    updatedUserName?: any | null;
    /**
     * 租户id
     * @type {number}
     * @memberof SysUser
     */
    tenantId?: any | null;
    /**
     * 账号
     * @type {string}
     * @memberof SysUser
     */
    account: any;
    /**
     * 密码（默认MD5加密）
     * @type {string}
     * @memberof SysUser
     */
    password: any;
    /**
     * 昵称
     * @type {string}
     * @memberof SysUser
     */
    nickName?: any | null;
    /**
     * 姓名
     * @type {string}
     * @memberof SysUser
     */
    name?: any | null;
    /**
     * 头像
     * @type {string}
     * @memberof SysUser
     */
    avatar?: any | null;
    /**
     * 生日
     * @type {Date}
     * @memberof SysUser
     */
    birthday?: any;
    /**
     * 
     * @type {Gender}
     * @memberof SysUser
     */
    sex?: any;
    /**
     * 邮箱
     * @type {string}
     * @memberof SysUser
     */
    email?: any | null;
    /**
     * 手机
     * @type {string}
     * @memberof SysUser
     */
    phone?: any | null;
    /**
     * 电话
     * @type {string}
     * @memberof SysUser
     */
    tel?: any | null;
    /**
     * 最后登录IP
     * @type {string}
     * @memberof SysUser
     */
    lastLoginIp?: any | null;
    /**
     * 最后登录时间
     * @type {Date}
     * @memberof SysUser
     */
    lastLoginTime?: any;
    /**
     * 
     * @type {AdminType}
     * @memberof SysUser
     */
    adminType?: any;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysUser
     */
    status?: any;
    /**
     * 多对多（角色）
     * @type {Array&lt;SysRole&gt;}
     * @memberof SysUser
     */
    sysRoles?: any | null;
    /**
     * 多对多中间表（用户-角色）
     * @type {Array&lt;SysUserRole&gt;}
     * @memberof SysUser
     */
    sysUserRoles?: any | null;
    /**
     * 多对多（机构）
     * @type {Array&lt;SysOrg&gt;}
     * @memberof SysUser
     */
    sysOrgs?: any | null;
    /**
     * 多对多中间表（用户-机构 数据范围）
     * @type {Array&lt;SysUserDataScope&gt;}
     * @memberof SysUser
     */
    sysUserDataScopes?: any | null;
}
