/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 组织机构表
 * @export
 * @interface SysOrg
 */
export interface SysOrg {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysOrg
     */
    id?: any;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysOrg
     */
    createdTime?: any | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof SysOrg
     */
    updatedTime?: any | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysOrg
     */
    createdUserId?: any | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysOrg
     */
    createdUserName?: any | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysOrg
     */
    updatedUserId?: any | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysOrg
     */
    updatedUserName?: any | null;
    /**
     * 租户id
     * @type {number}
     * @memberof SysOrg
     */
    tenantId?: any | null;
    /**
     * 父Id
     * @type {number}
     * @memberof SysOrg
     */
    pid?: any;
    /**
     * 父Ids
     * @type {string}
     * @memberof SysOrg
     */
    pids?: any | null;
    /**
     * 名称
     * @type {string}
     * @memberof SysOrg
     */
    name: any;
    /**
     * 编码
     * @type {string}
     * @memberof SysOrg
     */
    code: any;
    /**
     * 联系人
     * @type {string}
     * @memberof SysOrg
     */
    contacts?: any | null;
    /**
     * 电话
     * @type {string}
     * @memberof SysOrg
     */
    tel?: any | null;
    /**
     * 排序
     * @type {number}
     * @memberof SysOrg
     */
    sort?: any;
    /**
     * 备注
     * @type {string}
     * @memberof SysOrg
     */
    remark?: any | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysOrg
     */
    status?: any;
    /**
     * 多对多（用户）
     * @type {Array&lt;SysUser&gt;}
     * @memberof SysOrg
     */
    sysUsers?: any | null;
    /**
     * 多对多中间表（用户数据范围）
     * @type {Array&lt;SysUserDataScope&gt;}
     * @memberof SysOrg
     */
    sysUserDataScopes?: any | null;
    /**
     * 多对多（角色）
     * @type {Array&lt;SysRole&gt;}
     * @memberof SysOrg
     */
    sysRoles?: any | null;
    /**
     * 多对多中间表（角色数据范围）
     * @type {Array&lt;SysRoleDataScope&gt;}
     * @memberof SysOrg
     */
    sysRoleDataScopes?: any | null;
}
