/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateUserInput
 */
export interface UpdateUserInput {
    /**
     * 主键Id
     * @type {number}
     * @memberof UpdateUserInput
     */
    id: any;
    /**
     * 账号
     * @type {string}
     * @memberof UpdateUserInput
     */
    account: any;
    /**
     * 昵称
     * @type {string}
     * @memberof UpdateUserInput
     */
    nickName: any;
    /**
     * 姓名
     * @type {string}
     * @memberof UpdateUserInput
     */
    name: any;
    /**
     * 生日
     * @type {Date}
     * @memberof UpdateUserInput
     */
    birthday?: any | null;
    /**
     * 性别-男_1、女_2
     * @type {number}
     * @memberof UpdateUserInput
     */
    sex?: any;
    /**
     * 邮箱
     * @type {string}
     * @memberof UpdateUserInput
     */
    email: any;
    /**
     * 手机
     * @type {string}
     * @memberof UpdateUserInput
     */
    phone: any;
    /**
     * 电话
     * @type {string}
     * @memberof UpdateUserInput
     */
    tel?: any | null;
    /**
     * 
     * @type {EmpOutput2}
     * @memberof UpdateUserInput
     */
    sysEmpParam?: any;
}
