/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/Run2948/Admin.NET/'>https://gitee.com/Run2948/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateMenuInput
 */
export interface UpdateMenuInput {
    /**
     * 菜单Id
     * @type {number}
     * @memberof UpdateMenuInput
     */
    id: any;
    /**
     * 父Id
     * @type {number}
     * @memberof UpdateMenuInput
     */
    pid: any;
    /**
     * 
     * @type {MenuType}
     * @memberof UpdateMenuInput
     */
    type: any;
    /**
     * 名称
     * @type {string}
     * @memberof UpdateMenuInput
     */
    name?: any | null;
    /**
     * 编码
     * @type {string}
     * @memberof UpdateMenuInput
     */
    code?: any | null;
    /**
     * 图标
     * @type {string}
     * @memberof UpdateMenuInput
     */
    icon?: any | null;
    /**
     * 路由地址
     * @type {string}
     * @memberof UpdateMenuInput
     */
    router?: any | null;
    /**
     * 组件地址
     * @type {string}
     * @memberof UpdateMenuInput
     */
    component?: any | null;
    /**
     * 权限标识
     * @type {string}
     * @memberof UpdateMenuInput
     */
    permission?: any | null;
    /**
     * 应用分类（应用编码）
     * @type {string}
     * @memberof UpdateMenuInput
     */
    application?: any | null;
    /**
     * 
     * @type {MenuOpenType}
     * @memberof UpdateMenuInput
     */
    openType?: any;
    /**
     * 是否可见（Y-是，N-否）
     * @type {string}
     * @memberof UpdateMenuInput
     */
    visible?: any | null;
    /**
     * 内链地址
     * @type {string}
     * @memberof UpdateMenuInput
     */
    link?: any | null;
    /**
     * 重定向地址
     * @type {string}
     * @memberof UpdateMenuInput
     */
    redirect?: any | null;
    /**
     * 
     * @type {MenuWeight}
     * @memberof UpdateMenuInput
     */
    weight?: any;
    /**
     * 排序
     * @type {number}
     * @memberof UpdateMenuInput
     */
    sort?: any;
    /**
     * 备注
     * @type {string}
     * @memberof UpdateMenuInput
     */
    remark?: any | null;
}
