/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddDictTypeInput
 */
export interface AddDictTypeInput {
    /**
     * 名称
     * @type {string}
     * @memberof AddDictTypeInput
     */
    name: any;
    /**
     * 编码
     * @type {string}
     * @memberof AddDictTypeInput
     */
    code: any;
    /**
     * 排序
     * @type {number}
     * @memberof AddDictTypeInput
     */
    sort?: any;
    /**
     * 备注
     * @type {string}
     * @memberof AddDictTypeInput
     */
    remark?: any | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof AddDictTypeInput
     */
    status?: any;
}
