/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 员工职位参数
 * @export
 * @interface EmpPosOutput
 */
export interface EmpPosOutput {
    /**
     * 职位Id
     * @type {number}
     * @memberof EmpPosOutput
     */
    posId?: any;
    /**
     * 职位编码
     * @type {string}
     * @memberof EmpPosOutput
     */
    posCode?: any | null;
    /**
     * 职位名称
     * @type {string}
     * @memberof EmpPosOutput
     */
    posName?: any | null;
}
