/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 员工信息参数
 * @export
 * @interface EmpOutput
 */
export interface EmpOutput {
    /**
     * 工号
     * @type {string}
     * @memberof EmpOutput
     */
    jobNum?: any | null;
    /**
     * 机构id
     * @type {string}
     * @memberof EmpOutput
     */
    orgId?: any | null;
    /**
     * 机构名称
     * @type {string}
     * @memberof EmpOutput
     */
    orgName?: any | null;
    /**
     * 机构与职位信息
     * @type {Array&lt;EmpExtOrgPosOutput&gt;}
     * @memberof EmpOutput
     */
    extOrgPos?: any | null;
    /**
     * 职位信息
     * @type {Array&lt;EmpPosOutput&gt;}
     * @memberof EmpOutput
     */
    positions?: any | null;
}
