/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 租户表
 * @export
 * @interface SysTenant
 */
export interface SysTenant {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysTenant
     */
    id?: any;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysTenant
     */
    createdTime?: any | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof SysTenant
     */
    updatedTime?: any | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysTenant
     */
    createdUserId?: any | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysTenant
     */
    createdUserName?: any | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysTenant
     */
    updatedUserId?: any | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysTenant
     */
    updatedUserName?: any | null;
    /**
     * 公司名称
     * @type {string}
     * @memberof SysTenant
     */
    name: any;
    /**
     * 管理员名称
     * @type {string}
     * @memberof SysTenant
     */
    adminName: any;
    /**
     * 主机
     * @type {string}
     * @memberof SysTenant
     */
    host?: any | null;
    /**
     * 电子邮箱
     * @type {string}
     * @memberof SysTenant
     */
    email?: any | null;
    /**
     * 电话
     * @type {string}
     * @memberof SysTenant
     */
    phone?: any | null;
    /**
     * 数据库连接
     * @type {string}
     * @memberof SysTenant
     */
    connection?: any | null;
    /**
     * 架构
     * @type {string}
     * @memberof SysTenant
     */
    schema?: any | null;
    /**
     * 备注
     * @type {string}
     * @memberof SysTenant
     */
    remark?: any | null;
}
