/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET通用权限管理平台
 * 前后端分离架构，开箱即用，紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 用户角色表
 * @export
 * @interface SysUserRole
 */
export interface SysUserRole {
    /**
     * 用户Id
     * @type {number}
     * @memberof SysUserRole
     */
    sysUserId?: any;
    /**
     * 
     * @type {SysUser}
     * @memberof SysUserRole
     */
    sysUser?: any;
    /**
     * 系统角色Id
     * @type {number}
     * @memberof SysUserRole
     */
    sysRoleId?: any;
    /**
     * 
     * @type {SysRole}
     * @memberof SysUserRole
     */
    sysRole?: any;
}
